theme: jekyll-theme-minimal
title: [A way to finding fun niche and cheap places in Abu Dhabi]
description: [Discover Abu Dhabi beyond the tourist trail! Your ultimate insider’s guide to the city’s hidden gems quirky spots and affordable adventures tailored for residents seeking unique and fun experiences!]

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination (requires _posts folder)
paginate: 5

# SEO settings
url: "https://mohamedfadhyfaiz.github.io/hiddengemsofAD/"
